# Generated by Django 5.2.1 on 2025-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Cleaning', 'Cleaning'), ('Repair', 'Repair'), ('Painting', 'Painting'), ('Shifting', 'Shifting'), ('Plumbing', 'Plumbing'), ('Electric', 'Electric')], default='Cleaning', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
