export const services = [
  { name: 'Cleaning', icon: '🧹' },
  { name: 'Repair', icon: '🛠️' },
  { name: 'Painting', icon: '🎨' },
  { name: 'Shifting', icon: '🚚' },
  { name: 'Plumbing', icon: '🛁' },
  { name: 'Electric', icon: '⚡' },
];

export const businesses = [
  {
    id: 1,
    name: 'House Cleaning',
    category: 'Cleaning',
    person: 'Jenny Wilson',
    location: '255 Grand Park Ave, New York',
    image: 'https://source.unsplash.com/400x300/?cleaning,house',
    images: [
      'https://source.unsplash.com/400x300/?cleaning,house',
      'https://source.unsplash.com/400x300/?cleaning,room',
      'https://source.unsplash.com/400x300/?cleaning,kitchen',
      'https://source.unsplash.com/400x300/?cleaning,bathroom',
    ],
    description: 'Thorough house cleaning with eco-friendly products.',
  },
  {
    id: 2,
    name: 'Washing Clothes',
    category: 'Cleaning',
    person: 'Emma Potter',
    location: '525 N Tyson Street, New York',
    image: 'https://source.unsplash.com/400x300/?laundry',
    images: [
      'https://source.unsplash.com/400x300/?laundry,clothes',
      'https://source.unsplash.com/400x300/?washing,machine',
      'https://source.unsplash.com/400x300/?clean,clothes',
    ],
    description: 'Affordable clothes washing and folding services.',
  },
  {
    id: 3,
    name: 'House Repairing',
    category: 'Repair',
    person: 'Ronaldo Epric',
    location: '412 N Tyson Street, New York',
    image: 'https://source.unsplash.com/400x300/?repair,house',
    images: [
      'https://source.unsplash.com/400x300/?repair,wall',
      'https://source.unsplash.com/400x300/?repair,tools',
      'https://source.unsplash.com/400x300/?home,fixing',
    ],
    description: 'Expert home repair solutions for walls, roofs, and more.',
  },
  {
    id: 4,
    name: 'Bathroom Cleaning',
    category: 'Cleaning',
    person: 'Henry Wilson',
    location: '525 N Tyson Street, NC',
    image: 'https://source.unsplash.com/400x300/?bathroom,clean',
    images: [
      'https://source.unsplash.com/400x300/?bathroom,tiles',
      'https://source.unsplash.com/400x300/?bathroom,shower',
      'https://source.unsplash.com/400x300/?clean,bathroom',
    ],
    description: 'Deep bathroom sanitation with safe disinfectants.',
  },
  {
    id: 5,
    name: 'Floor Cleaning',
    category: 'Cleaning',
    person: 'Harry Will',
    location: 'Kallie Loop, NC',
    image: 'https://source.unsplash.com/400x300/?floor,cleaning',
    images: [
      'https://source.unsplash.com/400x300/?floor,tiles',
      'https://source.unsplash.com/400x300/?floor,mop',
    ],
    description: 'Sparkling floors using high-grade equipment.',
  },
  {
    id: 6,
    name: 'Packing & Shifting',
    category: 'Shifting',
    person: 'John Mathew',
    location: 'New Jersey',
    image: 'https://source.unsplash.com/400x300/?shifting,packing',
    images: [
      'https://source.unsplash.com/400x300/?packing,boxes',
      'https://source.unsplash.com/400x300/?moving,truck',
    ],
    description: 'Quick and safe packing and shifting solutions.',
  },
];
